### ISSUE TITLE
Runtime failure: regex

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#13]
Program always exits with the same error message:
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::regex_error: The expression contained mismatched ( and ).
Abort trap: 6
```
I can only reproduce this on my MacOS machine, not on Ubuntu. The way I've been dealing with this is to just remove the code that uses `comma_killer`.

**Comment by pcrain** [comment]
...well that's interesting. :o Looking into it!

**Comment by andrew-epstein** [comment]
Let me know if you need details on my environment. I've been using clang (NOT AppleClang), but let me check real quick if I can reproduce with g++.

**Comment by pcrain** [comment]
Looks like the curly brace needs to be escaped, not actually sure how it was working before!

**Comment by pcrain** [comment]
Escaped the curly brace, now should be working properly.

**Comment by andrew-epstein** [comment]
Confirmed, fixed!
