### ISSUE TITLE
SIGSEGV when file doesn't exist

### ISSUE THREAD

**Issue by andrew-epstein** [pcrain/slippc#18]
Any time a file that doesn't exist is passed to slippc, the program prints the "file does not exist" error message, and then this happens:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==59048==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000100d93588 bp 0x7ffeef14b950 sp 0x7ffeef14b920 T0)
==59048==The signal is caused by a READ memory access.
==59048==Hint: address points to the zero page.
    #0 0x100d93587 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) sanitizer_atomic_clang.h:80
    #1 0x100de20b5 in wrap__ZdaPv asan_new_delete.cc:205
    #2 0x100b55f6c in slip::Parser::~Parser() (slippc:x86_64+0x1000a2f6c)
    #3 0x100b2ebbc in main (slippc:x86_64+0x10007bbbc)
    #4 0x7fff5e0793d4 in start (libdyld.dylib:x86_64+0x163d4)
```
Looks like you're trying to delete an array that was never `new'ed`, because the file not existing means that code never executed. Should be fixable with a simple conditional.

**Comment by pcrain** [comment]
Whoops, I'm dumb. Fixed!

**Comment by andrew-epstein** [comment]
Confirmed, fixed.

**Comment by andrew-epstein** [comment]
Btw, would you be amenable to PR's? Just simple things, like fixing compiler warnings, applying some of clang-tidy's suggestions, etc.

**Comment by pcrain** [comment]
Pull requests are welcome! If there's any styling issues I'd want to manually review them before incorporating them. I'm all for fixing compiler warnings!
