### ISSUE TITLE
Support newest version of replay files

### ISSUE THREAD

**Issue by AlexanderHarrison** [pcrain/slippc#23]
I use this program extensively to compress all my slippi files, but it seems 3.8.0 isn't supported. Could you update this?

**Comment by pcrain** [comment]
Yep, the updates are in progress as we speak! I am trying to fix some lingering memory issues with the updated version of the compression algorithm while keeping things backwards compatible, but everything should be updated within the next few days! :smile:

**Comment by pcrain** [comment]
Done! :smiley:
