### ISSUE TITLE
std::filesystem has not been declared

### ISSUE THREAD

**Issue by NickCondron** [pcrain/slippc#25]
I get a weird issue claiming std::filesystem has not been declared in util.h. However there is a `#include <filesystem>` line there that should work. Googling told me that this is an issue for older versions of g++, but I have a new version that should fully support C++17.

```
nick@nick-lenovo:~/bin/slippc$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

nick@nick-lenovo:~/bin/slippc$ make static
Building file: src/parser.cpp
Invoking: GCC C++ Compiler
cc     src/parser.cpp -c -o build/parser.o
In file included from src/parser.h:9,
                 from src/parser.cpp:1:
src/util.h: In function ‘bool slip::makeDirectoryIfNotExists(const char*)’:
src/util.h:639:15: error: ‘std::filesystem’ has not been declared
  639 |   return std::filesystem::create_directories(path);
      |               ^~~~~~~~~~
make: *** [makefile:96: build/parser.o] Error 1

nick@nick-lenovo:~/bin/slippc$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
```

**Comment by pcrain** [comment]
Your logs indicate you have GCC 9.4.0 installed, which was released in March 2020. 😮 From the documentation page (https://gcc.gnu.org/gcc-9/changes.html), GCC release 9 includes only "Incomplete support for the C++17 Filesystem library and the Filesystem TS on Windows." For reference, I am using GCC 11.2.0. Please do try updating to a more recent release of GCC, and see if that helps! :smile:
